export const ADD_EVENT = 'ADD_EVENT'
export const GET_TODO = 'GET_TODO'
export const NAME_GOOGLE = 'NAME_GOOGLE'
export const NAME_EMAIL = 'NAME_EMAIL'
export const NAME_LOGOUT = 'NAME_LOGOUT'
export const ALL_MESSAGE = 'ALL_MESSAGE'
export const CHOICE_DOC = 'CHOICE_DOC'