export const ADD_EVENT = 'ADD_EVENT'
export const GET_DATA = 'GET_DATA'
export const NAME_GOOGLE = 'NAME_GOOGLE'
export const NAME_EMAIL = 'NAME_EMAIL'
export const NAME_LOGOUT = 'NAME_LOGOUT'
export const ADD_CREATE = 'ADD_CREATE'
export const CHOICE_DOC = 'CHOICE_DOC'